### ISSUE TITLE
"jsctl operator deploy" fails

### ISSUE THREAD

**Issue by amcginlay** [jetstack/jsctl#39]
Same result for MacOS as well as Linux:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd195b0]

goroutine 1 [running]:
k8s.io/client-go/kubernetes.NewForConfig(0x10a0650?)
	k8s.io/client-go@v0.25.2/kubernetes/clientset.go:422 +0x20
github.com/jetstack/jsctl/internal/kubernetes.NewKubeConfigApplier({0x10a0650?, 0x1c91b28?})
	github.com/jetstack/jsctl/internal/kubernetes/kubernetes.go:84 +0x2c
github.com/jetstack/jsctl/internal/command.operatorDeploy.func2({0x1308e60, 0x4000092e80}, {0x12f2540?, 0x400004ef00?, 0x0?})
	github.com/jetstack/jsctl/internal/command/operator.go:82 +0xd0
github.com/jetstack/jsctl/internal/command.run.func1(0x40000f4c80?, {0x1d4f0c0, 0x0, 0x0})
	github.com/jetstack/jsctl/internal/command/command.go:74 +0x1f0
github.com/spf13/cobra.(*Command).execute(0x40000f4c80, {0x1d4f0c0, 0x0, 0x0})
	github.com/spf13/cobra@v1.5.0/command.go:876 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x4000558f00)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x360
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.5.0/command.go:911
main.main()
	github.com/jetstack/jsctl/main.go:26 +0x1d0

**Comment by charlieegan3** [comment]
I hope that this has been fixed already in https://github.com/jetstack/jsctl/pull/35 - however, that's not yet been released. I'll keep this open until this is released.

**Comment by charlieegan3** [comment]
#35 was featured in the https://github.com/jetstack/jsctl/releases/tag/v0.1.10 release, I understand that this now should be fixed. Please do re-open if you have another case where this happens.
