### ISSUE TITLE
Step 2. Login and Configure the CLI shows conflicting messages to user

### ISSUE THREAD

**Issue by riazvm** [jetstack/jsctl#42]
jsctl auth login
redirects me to the browser, i use my jetstack email - the browser displays a message Unauthorized, where as the terminal shows Login succeeded. User gets two conflicting messages

**Comment by charlieegan3** [comment]
I'm not able to replicate this. Are you making sure that you're using the correct google account in your browser?

**Comment by charlieegan3** [comment]
I'm closing this as a dupe of https://github.com/jetstack/jsctl/issues/51. Feel free to re-open if you have issues after the next release.
