### ISSUE TITLE
Incorrect file permissions of the stored jsctl config & auth data

### ISSUE THREAD

**Issue by achuchev** [jetstack/jsctl#43]
I executed
> jsctl auth login
> jsctl config set organization xxx

as a result, I see that the config and auth data are store on the file system with 644 permissions. This is insecure. At most, the permissions must be 600.

https://github.com/jetstack/jsctl/blob/d57485d1c52b4bebb4b001f07e332d92c0024a71/internal/config/config.go#L96

Also, consider
- opening/writing files with symbolic link check. This is to avoid symbolic link attacks.
- do not load configuration/auth data if the file permissions are too open.

![image](https://user-images.githubusercontent.com/10324983/196041919-21e338c2-5db8-4abb-8187-87c35958730f.png)

**Comment by charlieegan3** [comment]
https://github.com/jetstack/jsctl/pull/47 should address this 🤞
