### ISSUE TITLE
Enhancement Request: Authentication on headless machines

### ISSUE THREAD

**Issue by achuchev** [jetstack/jsctl#50]
Authentication `jsctl` works well when it is installed on a machine with browser. In many cases, users are not having direct access from their workstations to the K8s clusters. Instead, they need to use bastion/jump hosts. Such hosts are usually headless (no browser), so the current authentication flow will not work. [OAuth 2.0 Device Authorization Grant](https://oauth.net/2/device-flow/)  is a flow which can help. 

PS: https://github.com/cli/oauth is a nice Go library from the Github.com developers.

**Comment by charlieegan3** [comment]
Hey, what do you think about https://github.com/jetstack/jsctl/pull/55 as something quick for the time being?

**Comment by charlieegan3** [comment]
@achuchev what do you think about this approach. Will it suffice to get you up and running?

**Comment by achuchev** [comment]
@charlieegan3 Hey. Apologies for not being responsive. I don't have time to check it out, but I think it's going to work for me. 
Don't hesitate to merge it.

**Comment by charlieegan3** [comment]
Hey, no problem. Thanks, I know it's not the ideal solution but it's something that I think would unblock you.

I'll get this merged.
