### ISSUE TITLE
inconsistent "uname -m" behaviour causing jsctl binary install problems on Apple Silicon

### ISSUE THREAD

**Issue by amcginlay** [jetstack/jsctl#51]
Instructions at https://platform.jetstack.io/org/gallant-wright/connect-cluster do not work from Ubuntu VM running on MacBook Pro M1.

1) "uname -m" from MacOS M1 returns "arm64" (works).
2) "uname -m" on **Ubuntu VM hosted on MacOS M1** returns "aarch64" (fails).
In case 2) there is no such Linux binary incorporating this name so the instructions fail.
Lowest impact solution may be to release copies of the Linux "arm64" binaries renamed as "aarch64".

Alternatively change:
`ASSET_REF=$(echo "jsctl-$VERSION-$(uname -s)-$(uname -m)" | tr '[:upper:]' '[:lower:]')`
to:
`ASSET_REF=$(echo "jsctl-$VERSION-$(uname -s)-$(uname -m | sed s/aarch64/arm64/g)" | tr '[:upper:]' '[:lower:]')`

**Comment by charlieegan3** [comment]
I have been trying to work out what all the different values will be on different operating systems and architectures. I have this table based on reports and some tests on cloud VMs.

| GOOS    | GOARCH | uname -s | uname -m |
|---------|--------|----------|----------|
| linux   | arm64  | Linux    | aarch64  |
| linux   | amd64  | Linux    | x86_64   |
| linux   | arm    | Linux    | armv7l   |
| darwin  | arm64  | Darwin   | arm64    |
| darwin  | amd64  | Darwin   | x86_64   |
| freebsd | amd64  | FreeBSD  | amd64    |
| windows | amd64  | BROKEN   | BROKEN   |
| windows | arm64  | BROKEN   | BROKEN   |

I propose that we:
* support i386 on windows only, not linux
* support 32 bit arm on linux only
* modify the installation flow for windows users where uname is unavailable
* address the issues with mismatched names with multiple goreleaser builds and archives

**Comment by achuchev** [comment]
It is worth exploring https://github.com/goreleaser/goreleaser and https://github.com/goreleaser/godownloader (Deprecated)
Godownloaded is deprecated, but it is able to generate a bash script which can simply installed by
`curl -sfL https://raw.githubusercontent.com/username/folder/example.sh | bash`

**Comment by charlieegan3** [comment]
I did consider a curl to bash option, however I think it's become pretty unfashionable for being potentially insecure. I'd like to avoid it for jsctl since Jetstack Secure is security software.

**Comment by charlieegan3** [comment]
https://github.com/jetstack/preflight-platform/pull/4391 is the link to the Jetstack internal fix for the UI where users get these instructions.
